GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/64ae4c0a84ca250d7b1345ea

###

PUT http://localhost:3001/api/persons/64a5cf26e7278ec50c9f7615

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Nigel", 
    "number": "326589008"
}

###

GET http://localhost:3001