GET http://localhost:3001/api/persons

###

GET http://localhost:3002/info

###

GET http://localhost:3002/api/persons/3

###

DELETE http://localhost:3002/api/persons/12615

###

POST http://localhost:3002/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Nigga", 
    "number": "326589008"
}

###

GET http://localhost:3001